apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-scraper
  template:
    metadata:
      labels:
        app: web-scraper
    spec:
      containers:
      - name: scraper
        image: kacperzaw/web-scraper:latest
        env:
        - name: MONGO_HOST
          value: mongodb-service
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "kacper"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "kacper"
---
apiVersion: v1
kind: Service
metadata:
  name: scraper-service
spec:
  type: ClusterIP
  selector:
    app: web-scraper
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000